import { Converter } from '@/types/converter';

export const converters: Converter[] = [
  // Common Converters
  {
    id: 'length',
    name: 'Length Converter',
    description: 'Convert between different units of length including meters, feet, inches, and more.',
    category: 'common',
    baseUnit: 'meter',
    precision: 8,
    units: [
      { name: 'Millimeter', symbol: 'mm', factor: 0.001 },
      { name: 'Centimeter', symbol: 'cm', factor: 0.01 },
      { name: 'Meter', symbol: 'm', factor: 1 },
      { name: 'Kilometer', symbol: 'km', factor: 1000 },
      { name: 'Inch', symbol: 'in', factor: 0.0254 },
      { name: 'Foot', symbol: 'ft', factor: 0.3048 },
      { name: 'Yard', symbol: 'yd', factor: 0.9144 },
      { name: 'Mile', symbol: 'mi', factor: 1609.34 },
      { name: 'Nautical Mile', symbol: 'nmi', factor: 1852 },
    ],
  },
  {
    id: 'weight',
    name: 'Weight and Mass Converter',
    description: 'Convert between different units of weight and mass including grams, pounds, ounces, and more.',
    category: 'common',
    baseUnit: 'gram',
    precision: 8,
    units: [
      { name: 'Milligram', symbol: 'mg', factor: 0.001 },
      { name: 'Gram', symbol: 'g', factor: 1 },
      { name: 'Kilogram', symbol: 'kg', factor: 1000 },
      { name: 'Ounce', symbol: 'oz', factor: 28.3495 },
      { name: 'Pound', symbol: 'lb', factor: 453.592 },
      { name: 'Stone', symbol: 'st', factor: 6350.29 },
      { name: 'Ton (Metric)', symbol: 't', factor: 1000000 },
      { name: 'Ton (US)', symbol: 'ton', factor: 907185 },
    ],
  },
  {
    id: 'volume',
    name: 'Volume Converter',
    description: 'Convert between different units of volume including liters, gallons, cups, and more.',
    category: 'common',
    baseUnit: 'liter',
    precision: 8,
    units: [
      { name: 'Milliliter', symbol: 'mL', factor: 0.001 },
      { name: 'Liter', symbol: 'L', factor: 1 },
      { name: 'Gallon (US)', symbol: 'gal', factor: 3.78541 },
      { name: 'Gallon (UK)', symbol: 'gal (UK)', factor: 4.54609 },
      { name: 'Quart (US)', symbol: 'qt', factor: 0.946353 },
      { name: 'Pint (US)', symbol: 'pt', factor: 0.473176 },
      { name: 'Cup (US)', symbol: 'cup', factor: 0.236588 },
      { name: 'Fluid Ounce (US)', symbol: 'fl oz', factor: 0.0295735 },
      { name: 'Tablespoon', symbol: 'tbsp', factor: 0.0147868 },
      { name: 'Teaspoon', symbol: 'tsp', factor: 0.00492892 },
    ],
  },
  {
    id: 'temperature',
    name: 'Temperature Converter',
    description: 'Convert between Celsius, Fahrenheit, Kelvin, and Rankine temperature scales.',
    category: 'common',
    baseUnit: 'celsius',
    precision: 4,
    units: [
      { name: 'Celsius', symbol: '°C', factor: 1, offset: 0 },
      { name: 'Fahrenheit', symbol: '°F', factor: 1.8, offset: 32 },
      { name: 'Kelvin', symbol: 'K', factor: 1, offset: 273.15 },
      { name: 'Rankine', symbol: '°R', factor: 1.8, offset: 491.67 },
    ],
  },
  {
    id: 'area',
    name: 'Area Converter',
    description: 'Convert between different units of area including square meters, acres, hectares, and more.',
    category: 'common',
    baseUnit: 'square meter',
    precision: 8,
    units: [
      { name: 'Square Millimeter', symbol: 'mm²', factor: 0.000001 },
      { name: 'Square Centimeter', symbol: 'cm²', factor: 0.0001 },
      { name: 'Square Meter', symbol: 'm²', factor: 1 },
      { name: 'Square Kilometer', symbol: 'km²', factor: 1000000 },
      { name: 'Square Inch', symbol: 'in²', factor: 0.00064516 },
      { name: 'Square Foot', symbol: 'ft²', factor: 0.092903 },
      { name: 'Square Yard', symbol: 'yd²', factor: 0.836127 },
      { name: 'Acre', symbol: 'ac', factor: 4046.86 },
      { name: 'Hectare', symbol: 'ha', factor: 10000 },
    ],
  },
  {
    id: 'pressure',
    name: 'Pressure Converter',
    description: 'Convert between different units of pressure including Pascal, PSI, bar, and more.',
    category: 'common',
    baseUnit: 'pascal',
    precision: 8,
    units: [
      { name: 'Pascal', symbol: 'Pa', factor: 1 },
      { name: 'Kilopascal', symbol: 'kPa', factor: 1000 },
      { name: 'Megapascal', symbol: 'MPa', factor: 1000000 },
      { name: 'Bar', symbol: 'bar', factor: 100000 },
      { name: 'PSI', symbol: 'psi', factor: 6894.76 },
      { name: 'Atmosphere', symbol: 'atm', factor: 101325 },
      { name: 'Torr', symbol: 'Torr', factor: 133.322 },
      { name: 'mmHg', symbol: 'mmHg', factor: 133.322 },
    ],
  },
  {
    id: 'energy',
    name: 'Energy Converter',
    description: 'Convert between different units of energy including Joules, calories, BTU, and more.',
    category: 'common',
    baseUnit: 'joule',
    precision: 8,
    units: [
      { name: 'Joule', symbol: 'J', factor: 1 },
      { name: 'Kilojoule', symbol: 'kJ', factor: 1000 },
      { name: 'Calorie', symbol: 'cal', factor: 4.184 },
      { name: 'Kilocalorie', symbol: 'kcal', factor: 4184 },
      { name: 'BTU', symbol: 'BTU', factor: 1055.06 },
      { name: 'Watt Hour', symbol: 'Wh', factor: 3600 },
      { name: 'Kilowatt Hour', symbol: 'kWh', factor: 3600000 },
      { name: 'Foot-pound', symbol: 'ft⋅lb', factor: 1.35582 },
    ],
  },
  {
    id: 'power',
    name: 'Power Converter',
    description: 'Convert between different units of power including Watts, horsepower, BTU/hr, and more.',
    category: 'common',
    baseUnit: 'watt',
    precision: 8,
    units: [
      { name: 'Watt', symbol: 'W', factor: 1 },
      { name: 'Kilowatt', symbol: 'kW', factor: 1000 },
      { name: 'Megawatt', symbol: 'MW', factor: 1000000 },
      { name: 'Horsepower (Mechanical)', symbol: 'hp', factor: 745.7 },
      { name: 'Horsepower (Metric)', symbol: 'hp (M)', factor: 735.5 },
      { name: 'BTU per Hour', symbol: 'BTU/h', factor: 0.293071 },
      { name: 'Foot-pound per Second', symbol: 'ft⋅lb/s', factor: 1.35582 },
    ],
  },
  {
    id: 'speed',
    name: 'Speed Converter',
    description: 'Convert between different units of speed including m/s, km/h, mph, and more.',
    category: 'common',
    baseUnit: 'meter per second',
    precision: 8,
    units: [
      { name: 'Meter per Second', symbol: 'm/s', factor: 1 },
      { name: 'Kilometer per Hour', symbol: 'km/h', factor: 0.277778 },
      { name: 'Mile per Hour', symbol: 'mph', factor: 0.44704 },
      { name: 'Foot per Second', symbol: 'ft/s', factor: 0.3048 },
      { name: 'Knot', symbol: 'kn', factor: 0.514444 },
      { name: 'Mach', symbol: 'M', factor: 343 },
    ],
  },
  {
    id: 'time',
    name: 'Time Converter',
    description: 'Convert between different units of time including seconds, minutes, hours, days, and more.',
    category: 'common',
    baseUnit: 'second',
    precision: 8,
    units: [
      { name: 'Nanosecond', symbol: 'ns', factor: 0.000000001 },
      { name: 'Microsecond', symbol: 'μs', factor: 0.000001 },
      { name: 'Millisecond', symbol: 'ms', factor: 0.001 },
      { name: 'Second', symbol: 's', factor: 1 },
      { name: 'Minute', symbol: 'min', factor: 60 },
      { name: 'Hour', symbol: 'h', factor: 3600 },
      { name: 'Day', symbol: 'd', factor: 86400 },
      { name: 'Week', symbol: 'wk', factor: 604800 },
      { name: 'Month (30 days)', symbol: 'mo', factor: 2592000 },
      { name: 'Year (365 days)', symbol: 'yr', factor: 31536000 },
    ],
  },
  {
    id: 'angle',
    name: 'Angle Converter',
    description: 'Convert between different units of angle including degrees, radians, gradians, and more.',
    category: 'common',
    baseUnit: 'degree',
    precision: 8,
    units: [
      { name: 'Degree', symbol: '°', factor: 1 },
      { name: 'Radian', symbol: 'rad', factor: 57.2958 },
      { name: 'Gradian', symbol: 'grad', factor: 0.9 },
      { name: 'Milliradian', symbol: 'mrad', factor: 0.0572958 },
      { name: 'Minute of Arc', symbol: "'", factor: 0.0166667 },
      { name: 'Second of Arc', symbol: '"', factor: 0.000277778 },
    ],
  },
  {
    id: 'fuel-consumption',
    name: 'Fuel Consumption Converter',
    description: 'Convert between different units of fuel consumption including L/100km, MPG, and more.',
    category: 'common',
    baseUnit: 'liter per 100 kilometer',
    precision: 6,
    units: [
      { name: 'Liter per 100 Kilometer', symbol: 'L/100km', factor: 1 },
      { name: 'Mile per Gallon (US)', symbol: 'MPG (US)', factor: 235.214 },
      { name: 'Mile per Gallon (UK)', symbol: 'MPG (UK)', factor: 282.481 },
      { name: 'Kilometer per Liter', symbol: 'km/L', factor: 100 },
    ],
  },
  
  // Engineering Converters
  {
    id: 'velocity-angular',
    name: 'Angular Velocity Converter',
    description: 'Convert between different units of angular velocity including rad/s, RPM, and more.',
    category: 'engineering',
    baseUnit: 'radian per second',
    precision: 8,
    units: [
      { name: 'Radian per Second', symbol: 'rad/s', factor: 1 },
      { name: 'Revolution per Minute', symbol: 'RPM', factor: 0.104720 },
      { name: 'Revolution per Second', symbol: 'rev/s', factor: 6.28319 },
      { name: 'Degree per Second', symbol: '°/s', factor: 0.0174533 },
    ],
  },
  {
    id: 'acceleration',
    name: 'Acceleration Converter',
    description: 'Convert between different units of acceleration including m/s², ft/s², and more.',
    category: 'engineering',
    baseUnit: 'meter per second squared',
    precision: 8,
    units: [
      { name: 'Meter per Second²', symbol: 'm/s²', factor: 1 },
      { name: 'Foot per Second²', symbol: 'ft/s²', factor: 0.3048 },
      { name: 'G-force', symbol: 'g', factor: 9.80665 },
      { name: 'Galileo', symbol: 'Gal', factor: 0.01 },
    ],
  },
  {
    id: 'acceleration-angular',
    name: 'Angular Acceleration Converter',
    description: 'Convert between different units of angular acceleration including rad/s², rev/s², and more.',
    category: 'engineering',
    baseUnit: 'radian per second squared',
    precision: 8,
    units: [
      { name: 'Radian per Second²', symbol: 'rad/s²', factor: 1 },
      { name: 'Revolution per Second²', symbol: 'rev/s²', factor: 6.28319 },
      { name: 'Revolution per Minute²', symbol: 'rev/min²', factor: 0.00109662 },
    ],
  },
  {
    id: 'density',
    name: 'Density Converter',
    description: 'Convert between different units of density including kg/m³, g/cm³, lb/ft³, and more.',
    category: 'engineering',
    baseUnit: 'kilogram per cubic meter',
    precision: 8,
    units: [
      { name: 'Kilogram per Cubic Meter', symbol: 'kg/m³', factor: 1 },
      { name: 'Gram per Cubic Centimeter', symbol: 'g/cm³', factor: 1000 },
      { name: 'Pound per Cubic Foot', symbol: 'lb/ft³', factor: 16.0185 },
      { name: 'Pound per Cubic Inch', symbol: 'lb/in³', factor: 27679.9 },
    ],
  },
  {
    id: 'specific-volume',
    name: 'Specific Volume Converter',
    description: 'Convert between different units of specific volume including m³/kg, ft³/lb, and more.',
    category: 'engineering',
    baseUnit: 'cubic meter per kilogram',
    precision: 8,
    units: [
      { name: 'Cubic Meter per Kilogram', symbol: 'm³/kg', factor: 1 },
      { name: 'Cubic Foot per Pound', symbol: 'ft³/lb', factor: 0.0624280 },
      { name: 'Cubic Inch per Pound', symbol: 'in³/lb', factor: 0.0000361273 },
    ],
  },
  {
    id: 'moment-of-inertia',
    name: 'Moment of Inertia Converter',
    description: 'Convert between different units of moment of inertia including kg⋅m², lb⋅ft², and more.',
    category: 'engineering',
    baseUnit: 'kilogram square meter',
    precision: 8,
    units: [
      { name: 'Kilogram Square Meter', symbol: 'kg⋅m²', factor: 1 },
      { name: 'Pound Square Foot', symbol: 'lb⋅ft²', factor: 0.0421401 },
      { name: 'Pound Square Inch', symbol: 'lb⋅in²', factor: 0.000292640 },
      { name: 'Ounce Square Inch', symbol: 'oz⋅in²', factor: 0.0000183 },
    ],
  },
  {
    id: 'moment-of-force',
    name: 'Moment of Force Converter',
    description: 'Convert between different units of moment of force including N⋅m, lb⋅ft, and more.',
    category: 'engineering',
    baseUnit: 'newton meter',
    precision: 8,
    units: [
      { name: 'Newton Meter', symbol: 'N⋅m', factor: 1 },
      { name: 'Pound-foot', symbol: 'lb⋅ft', factor: 1.35582 },
      { name: 'Pound-inch', symbol: 'lb⋅in', factor: 0.112985 },
      { name: 'Kilogram-force Meter', symbol: 'kgf⋅m', factor: 9.80665 },
    ],
  },
  {
    id: 'torque',
    name: 'Torque Converter',
    description: 'Convert between different units of torque including N⋅m, lb⋅ft, dyne⋅cm, and more.',
    category: 'engineering',
    baseUnit: 'newton meter',
    precision: 8,
    units: [
      { name: 'Newton Meter', symbol: 'N⋅m', factor: 1 },
      { name: 'Pound-foot', symbol: 'lb⋅ft', factor: 1.35582 },
      { name: 'Pound-inch', symbol: 'lb⋅in', factor: 0.112985 },
      { name: 'Dyne Centimeter', symbol: 'dyn⋅cm', factor: 0.0000001 },
      { name: 'Kilogram-force Meter', symbol: 'kgf⋅m', factor: 9.80665 },
    ],
  },
  {
    id: 'force',
    name: 'Force Converter',
    description: 'Convert between different units of force including Newtons, pounds-force, dyne, and more.',
    category: 'engineering',
    baseUnit: 'newton',
    precision: 8,
    units: [
      { name: 'Newton', symbol: 'N', factor: 1 },
      { name: 'Kilonewton', symbol: 'kN', factor: 1000 },
      { name: 'Pound-force', symbol: 'lbf', factor: 4.44822 },
      { name: 'Dyne', symbol: 'dyn', factor: 0.00001 },
      { name: 'Kilogram-force', symbol: 'kgf', factor: 9.80665 },
      { name: 'Poundal', symbol: 'pdl', factor: 0.138255 },
    ],
  },

  // Heat Converters
  {
    id: 'fuel-efficiency-mass',
    name: 'Fuel Efficiency Mass Converter',
    description: 'Convert between different mass-based fuel efficiency units.',
    category: 'heat',
    baseUnit: 'kilometer per kilogram',
    precision: 6,
    units: [
      { name: 'Kilometer per Kilogram', symbol: 'km/kg', factor: 1 },
      { name: 'Mile per Pound', symbol: 'mi/lb', factor: 2.20462 },
      { name: 'Meter per Gram', symbol: 'm/g', factor: 0.001 },
    ],
  },
  {
    id: 'fuel-efficiency-volume',
    name: 'Fuel Efficiency Volume Converter',
    description: 'Convert between different volume-based fuel efficiency units.',
    category: 'heat',
    baseUnit: 'kilometer per liter',
    precision: 6,
    units: [
      { name: 'Kilometer per Liter', symbol: 'km/L', factor: 1 },
      { name: 'Mile per Gallon (US)', symbol: 'MPG (US)', factor: 2.35214 },
      { name: 'Mile per Gallon (UK)', symbol: 'MPG (UK)', factor: 2.82481 },
    ],
  },
  {
    id: 'temperature-interval',
    name: 'Temperature Interval Converter',
    description: 'Convert between different temperature interval units.',
    category: 'heat',
    baseUnit: 'kelvin',
    precision: 6,
    units: [
      { name: 'Kelvin', symbol: 'K', factor: 1 },
      { name: 'Celsius', symbol: '°C', factor: 1 },
      { name: 'Fahrenheit', symbol: '°F', factor: 0.555556 },
      { name: 'Rankine', symbol: '°R', factor: 0.555556 },
    ],
  },
  {
    id: 'thermal-expansion',
    name: 'Thermal Expansion Converter',
    description: 'Convert between different thermal expansion coefficient units.',
    category: 'heat',
    baseUnit: 'per kelvin',
    precision: 10,
    units: [
      { name: 'per Kelvin', symbol: '/K', factor: 1 },
      { name: 'per Celsius', symbol: '/°C', factor: 1 },
      { name: 'per Fahrenheit', symbol: '/°F', factor: 1.8 },
      { name: 'per Rankine', symbol: '/°R', factor: 1.8 },
    ],
  },
  {
    id: 'thermal-resistance',
    name: 'Thermal Resistance Converter',
    description: 'Convert between different thermal resistance units.',
    category: 'heat',
    baseUnit: 'kelvin per watt',
    precision: 8,
    units: [
      { name: 'Kelvin per Watt', symbol: 'K/W', factor: 1 },
      { name: 'Celsius per Watt', symbol: '°C/W', factor: 1 },
      { name: 'Fahrenheit per BTU/h', symbol: '°F/(BTU/h)', factor: 0.52753 },
    ],
  },
  {
    id: 'thermal-conductivity',
    name: 'Thermal Conductivity Converter',
    description: 'Convert between different thermal conductivity units.',
    category: 'heat',
    baseUnit: 'watt per meter kelvin',
    precision: 8,
    units: [
      { name: 'Watt per Meter Kelvin', symbol: 'W/(m⋅K)', factor: 1 },
      { name: 'BTU per Hour Foot Fahrenheit', symbol: 'BTU/(h⋅ft⋅°F)', factor: 1.73073 },
      { name: 'Calorie per Second Centimeter Celsius', symbol: 'cal/(s⋅cm⋅°C)', factor: 418.4 },
    ],
  },
  {
    id: 'specific-heat-capacity',
    name: 'Specific Heat Capacity Converter',
    description: 'Convert between different specific heat capacity units.',
    category: 'heat',
    baseUnit: 'joule per kilogram kelvin',
    precision: 8,
    units: [
      { name: 'Joule per Kilogram Kelvin', symbol: 'J/(kg⋅K)', factor: 1 },
      { name: 'BTU per Pound Fahrenheit', symbol: 'BTU/(lb⋅°F)', factor: 4186.8 },
      { name: 'Calorie per Gram Celsius', symbol: 'cal/(g⋅°C)', factor: 4184 },
    ],
  },
  {
    id: 'heat-density',
    name: 'Heat Density Converter',
    description: 'Convert between different heat density units.',
    category: 'heat',
    baseUnit: 'joule per cubic meter',
    precision: 8,
    units: [
      { name: 'Joule per Cubic Meter', symbol: 'J/m³', factor: 1 },
      { name: 'BTU per Cubic Foot', symbol: 'BTU/ft³', factor: 37258.9 },
      { name: 'Calorie per Cubic Centimeter', symbol: 'cal/cm³', factor: 4184000 },
    ],
  },
  {
    id: 'heat-flux-density',
    name: 'Heat Flux Density Converter',
    description: 'Convert between different heat flux density units.',
    category: 'heat',
    baseUnit: 'watt per square meter',
    precision: 8,
    units: [
      { name: 'Watt per Square Meter', symbol: 'W/m²', factor: 1 },
      { name: 'BTU per Hour Square Foot', symbol: 'BTU/(h⋅ft²)', factor: 3.15459 },
      { name: 'Calorie per Second Square Centimeter', symbol: 'cal/(s⋅cm²)', factor: 41840 },
    ],
  },
  {
    id: 'heat-transfer-coefficient',
    name: 'Heat Transfer Coefficient Converter',
    description: 'Convert between different heat transfer coefficient units.',
    category: 'heat',
    baseUnit: 'watt per square meter kelvin',
    precision: 8,
    units: [
      { name: 'Watt per Square Meter Kelvin', symbol: 'W/(m²⋅K)', factor: 1 },
      { name: 'BTU per Hour Square Foot Fahrenheit', symbol: 'BTU/(h⋅ft²⋅°F)', factor: 5.67826 },
      { name: 'Calorie per Second Square Centimeter Celsius', symbol: 'cal/(s⋅cm²⋅°C)', factor: 41840 },
    ],
  },

  // Fluids Converters
  {
    id: 'flow',
    name: 'Flow Converter',
    description: 'Convert between different flow rate units including L/min, gal/min, m³/s, and more.',
    category: 'fluids',
    baseUnit: 'cubic meter per second',
    precision: 8,
    units: [
      { name: 'Cubic Meter per Second', symbol: 'm³/s', factor: 1 },
      { name: 'Liter per Second', symbol: 'L/s', factor: 0.001 },
      { name: 'Liter per Minute', symbol: 'L/min', factor: 0.0000166667 },
      { name: 'Gallon per Minute (US)', symbol: 'GPM', factor: 0.0000630902 },
      { name: 'Gallon per Hour (US)', symbol: 'GPH', factor: 0.00000105150 },
      { name: 'Cubic Foot per Second', symbol: 'ft³/s', factor: 0.0283168 },
      { name: 'Cubic Foot per Minute', symbol: 'CFM', factor: 0.000471947 },
    ],
  },
  {
    id: 'flow-mass',
    name: 'Mass Flow Converter',
    description: 'Convert between different mass flow rate units including kg/s, lb/min, and more.',
    category: 'fluids',
    baseUnit: 'kilogram per second',
    precision: 8,
    units: [
      { name: 'Kilogram per Second', symbol: 'kg/s', factor: 1 },
      { name: 'Gram per Second', symbol: 'g/s', factor: 0.001 },
      { name: 'Pound per Second', symbol: 'lb/s', factor: 0.453592 },
      { name: 'Pound per Minute', symbol: 'lb/min', factor: 0.00755987 },
      { name: 'Pound per Hour', symbol: 'lb/h', factor: 0.000125998 },
      { name: 'Ton per Hour', symbol: 't/h', factor: 0.277778 },
    ],
  },
  {
    id: 'flow-molar',
    name: 'Molar Flow Converter',
    description: 'Convert between different molar flow rate units including mol/s, kmol/h, and more.',
    category: 'fluids',
    baseUnit: 'mole per second',
    precision: 8,
    units: [
      { name: 'Mole per Second', symbol: 'mol/s', factor: 1 },
      { name: 'Millimole per Second', symbol: 'mmol/s', factor: 0.001 },
      { name: 'Kilomole per Second', symbol: 'kmol/s', factor: 1000 },
      { name: 'Mole per Minute', symbol: 'mol/min', factor: 0.0166667 },
      { name: 'Mole per Hour', symbol: 'mol/h', factor: 0.000277778 },
      { name: 'Kilomole per Hour', symbol: 'kmol/h', factor: 0.277778 },
    ],
  },
  {
    id: 'mass-flux-density',
    name: 'Mass Flux Density Converter',
    description: 'Convert between different mass flux density units.',
    category: 'fluids',
    baseUnit: 'kilogram per square meter second',
    precision: 8,
    units: [
      { name: 'Kilogram per Square Meter Second', symbol: 'kg/(m²⋅s)', factor: 1 },
      { name: 'Gram per Square Centimeter Second', symbol: 'g/(cm²⋅s)', factor: 10 },
      { name: 'Pound per Square Foot Second', symbol: 'lb/(ft²⋅s)', factor: 4.88243 },
    ],
  },
  {
    id: 'concentration-molar',
    name: 'Molar Concentration Converter',
    description: 'Convert between different molar concentration units including mol/L, M, and more.',
    category: 'fluids',
    baseUnit: 'mole per cubic meter',
    precision: 8,
    units: [
      { name: 'Mole per Cubic Meter', symbol: 'mol/m³', factor: 1 },
      { name: 'Mole per Liter', symbol: 'mol/L', factor: 1000 },
      { name: 'Millimole per Liter', symbol: 'mmol/L', factor: 1 },
      { name: 'Molar', symbol: 'M', factor: 1000 },
      { name: 'Millimolar', symbol: 'mM', factor: 1 },
    ],
  },
  {
    id: 'concentration-solution',
    name: 'Solution Concentration Converter',
    description: 'Convert between different solution concentration units including %, ppm, and more.',
    category: 'fluids',
    baseUnit: 'percent',
    precision: 8,
    units: [
      { name: 'Percent', symbol: '%', factor: 1 },
      { name: 'Parts per Million', symbol: 'ppm', factor: 0.0001 },
      { name: 'Parts per Billion', symbol: 'ppb', factor: 0.0000001 },
      { name: 'Parts per Trillion', symbol: 'ppt', factor: 0.0000000001 },
    ],
  },
  {
    id: 'viscosity-dynamic',
    name: 'Dynamic Viscosity Converter',
    description: 'Convert between different dynamic viscosity units including Pa⋅s, cP, and more.',
    category: 'fluids',
    baseUnit: 'pascal second',
    precision: 8,
    units: [
      { name: 'Pascal Second', symbol: 'Pa⋅s', factor: 1 },
      { name: 'Poise', symbol: 'P', factor: 0.1 },
      { name: 'Centipoise', symbol: 'cP', factor: 0.001 },
      { name: 'Pound per Foot Second', symbol: 'lb/(ft⋅s)', factor: 1.48816 },
    ],
  },
  {
    id: 'viscosity-kinematic',
    name: 'Kinematic Viscosity Converter',
    description: 'Convert between different kinematic viscosity units including m²/s, St, and more.',
    category: 'fluids',
    baseUnit: 'square meter per second',
    precision: 8,
    units: [
      { name: 'Square Meter per Second', symbol: 'm²/s', factor: 1 },
      { name: 'Stokes', symbol: 'St', factor: 0.0001 },
      { name: 'Centistokes', symbol: 'cSt', factor: 0.000001 },
      { name: 'Square Foot per Second', symbol: 'ft²/s', factor: 0.092903 },
    ],
  },
  {
    id: 'surface-tension',
    name: 'Surface Tension Converter',
    description: 'Convert between different surface tension units including N/m, dyn/cm, and more.',
    category: 'fluids',
    baseUnit: 'newton per meter',
    precision: 8,
    units: [
      { name: 'Newton per Meter', symbol: 'N/m', factor: 1 },
      { name: 'Dyne per Centimeter', symbol: 'dyn/cm', factor: 0.001 },
      { name: 'Pound-force per Inch', symbol: 'lbf/in', factor: 175.127 },
      { name: 'Millinewton per Meter', symbol: 'mN/m', factor: 0.001 },
    ],
  },
  {
    id: 'permeability',
    name: 'Permeability Converter',
    description: 'Convert between different permeability units including m², darcy, and more.',
    category: 'fluids',
    baseUnit: 'square meter',
    precision: 15,
    units: [
      { name: 'Square Meter', symbol: 'm²', factor: 1 },
      { name: 'Darcy', symbol: 'D', factor: 9.869233e-13 },
      { name: 'Millidarcy', symbol: 'mD', factor: 9.869233e-16 },
      { name: 'Square Centimeter', symbol: 'cm²', factor: 0.0001 },
    ],
  },

  // Light Converters
  {
    id: 'luminance',
    name: 'Luminance Converter',
    description: 'Convert between different luminance units including cd/m², nit, and more.',
    category: 'light',
    baseUnit: 'candela per square meter',
    precision: 8,
    units: [
      { name: 'Candela per Square Meter', symbol: 'cd/m²', factor: 1 },
      { name: 'Nit', symbol: 'nt', factor: 1 },
      { name: 'Stilb', symbol: 'sb', factor: 10000 },
      { name: 'Lambert', symbol: 'L', factor: 3183.1 },
      { name: 'Foot-lambert', symbol: 'fL', factor: 3.42626 },
    ],
  },
  {
    id: 'luminous-intensity',
    name: 'Luminous Intensity Converter',
    description: 'Convert between different luminous intensity units including candela, candlepower, and more.',
    category: 'light',
    baseUnit: 'candela',
    precision: 8,
    units: [
      { name: 'Candela', symbol: 'cd', factor: 1 },
      { name: 'Candlepower', symbol: 'cp', factor: 1 },
      { name: 'Hefnerkerze', symbol: 'HK', factor: 0.9 },
      { name: 'International Candle', symbol: 'IC', factor: 1.02 },
    ],
  },
  {
    id: 'illumination',
    name: 'Illumination Converter',
    description: 'Convert between different illumination units including lux, foot-candle, and more.',
    category: 'light',
    baseUnit: 'lux',
    precision: 8,
    units: [
      { name: 'Lux', symbol: 'lx', factor: 1 },
      { name: 'Foot-candle', symbol: 'fc', factor: 10.764 },
      { name: 'Phot', symbol: 'ph', factor: 10000 },
      { name: 'Nox', symbol: 'nx', factor: 0.001 },
    ],
  },
  {
    id: 'digital-image-resolution',
    name: 'Digital Image Resolution Converter',
    description: 'Convert between different digital image resolution units including DPI, PPI, and more.',
    category: 'light',
    baseUnit: 'dot per inch',
    precision: 4,
    units: [
      { name: 'Dot per Inch', symbol: 'DPI', factor: 1 },
      { name: 'Pixel per Inch', symbol: 'PPI', factor: 1 },
      { name: 'Dot per Centimeter', symbol: 'DPC', factor: 2.54 },
      { name: 'Pixel per Centimeter', symbol: 'PPC', factor: 2.54 },
    ],
  },
  {
    id: 'frequency-wavelength',
    name: 'Frequency Wavelength Converter',
    description: 'Convert between frequency and wavelength for electromagnetic radiation.',
    category: 'light',
    baseUnit: 'hertz',
    precision: 8,
    units: [
      { name: 'Hertz', symbol: 'Hz', factor: 1 },
      { name: 'Kilohertz', symbol: 'kHz', factor: 1000 },
      { name: 'Megahertz', symbol: 'MHz', factor: 1000000 },
      { name: 'Gigahertz', symbol: 'GHz', factor: 1000000000 },
      { name: 'Terahertz', symbol: 'THz', factor: 1000000000000 },
    ],
  },

  // Electricity Converters
  {
    id: 'charge',
    name: 'Electric Charge Converter',
    description: 'Convert between different electric charge units including coulomb, ampere-hour, and more.',
    category: 'electricity',
    baseUnit: 'coulomb',
    precision: 8,
    units: [
      { name: 'Coulomb', symbol: 'C', factor: 1 },
      { name: 'Ampere Hour', symbol: 'Ah', factor: 3600 },
      { name: 'Ampere Second', symbol: 'As', factor: 1 },
      { name: 'Milliampere Hour', symbol: 'mAh', factor: 3.6 },
      { name: 'Elementary Charge', symbol: 'e', factor: 1.602176e-19 },
    ],
  },
  {
    id: 'linear-charge-density',
    name: 'Linear Charge Density Converter',
    description: 'Convert between different linear charge density units.',
    category: 'electricity',
    baseUnit: 'coulomb per meter',
    precision: 8,
    units: [
      { name: 'Coulomb per Meter', symbol: 'C/m', factor: 1 },
      { name: 'Coulomb per Centimeter', symbol: 'C/cm', factor: 100 },
      { name: 'Coulomb per Inch', symbol: 'C/in', factor: 39.3701 },
    ],
  },
  {
    id: 'surface-charge-density',
    name: 'Surface Charge Density Converter',
    description: 'Convert between different surface charge density units.',
    category: 'electricity',
    baseUnit: 'coulomb per square meter',
    precision: 8,
    units: [
      { name: 'Coulomb per Square Meter', symbol: 'C/m²', factor: 1 },
      { name: 'Coulomb per Square Centimeter', symbol: 'C/cm²', factor: 10000 },
      { name: 'Coulomb per Square Inch', symbol: 'C/in²', factor: 1550 },
    ],
  },
  {
    id: 'volume-charge-density',
    name: 'Volume Charge Density Converter',
    description: 'Convert between different volume charge density units.',
    category: 'electricity',
    baseUnit: 'coulomb per cubic meter',
    precision: 8,
    units: [
      { name: 'Coulomb per Cubic Meter', symbol: 'C/m³', factor: 1 },
      { name: 'Coulomb per Cubic Centimeter', symbol: 'C/cm³', factor: 1000000 },
      { name: 'Coulomb per Cubic Inch', symbol: 'C/in³', factor: 61023.7 },
    ],
  },
  {
    id: 'current',
    name: 'Electric Current Converter',
    description: 'Convert between different electric current units including ampere, milliampere, and more.',
    category: 'electricity',
    baseUnit: 'ampere',
    precision: 8,
    units: [
      { name: 'Ampere', symbol: 'A', factor: 1 },
      { name: 'Milliampere', symbol: 'mA', factor: 0.001 },
      { name: 'Microampere', symbol: 'μA', factor: 0.000001 },
      { name: 'Kiloampere', symbol: 'kA', factor: 1000 },
      { name: 'Abampere', symbol: 'aA', factor: 10 },
      { name: 'Statampere', symbol: 'stA', factor: 3.33564e-10 },
    ],
  },
  {
    id: 'linear-current-density',
    name: 'Linear Current Density Converter',
    description: 'Convert between different linear current density units.',
    category: 'electricity',
    baseUnit: 'ampere per meter',
    precision: 8,
    units: [
      { name: 'Ampere per Meter', symbol: 'A/m', factor: 1 },
      { name: 'Ampere per Centimeter', symbol: 'A/cm', factor: 100 },
      { name: 'Ampere per Inch', symbol: 'A/in', factor: 39.3701 },
    ],
  },
  {
    id: 'surface-current-density',
    name: 'Surface Current Density Converter',
    description: 'Convert between different surface current density units.',
    category: 'electricity',
    baseUnit: 'ampere per meter',
    precision: 8,
    units: [
      { name: 'Ampere per Meter', symbol: 'A/m', factor: 1 },
      { name: 'Ampere per Centimeter', symbol: 'A/cm', factor: 100 },
      { name: 'Ampere per Inch', symbol: 'A/in', factor: 39.3701 },
    ],
  },
  {
    id: 'electric-field-strength',
    name: 'Electric Field Strength Converter',
    description: 'Convert between different electric field strength units.',
    category: 'electricity',
    baseUnit: 'volt per meter',
    precision: 8,
    units: [
      { name: 'Volt per Meter', symbol: 'V/m', factor: 1 },
      { name: 'Volt per Centimeter', symbol: 'V/cm', factor: 100 },
      { name: 'Volt per Inch', symbol: 'V/in', factor: 39.3701 },
      { name: 'Kilovolt per Meter', symbol: 'kV/m', factor: 1000 },
    ],
  },
  {
    id: 'electric-potential',
    name: 'Electric Potential Converter',
    description: 'Convert between different electric potential units including volt, millivolt, and more.',
    category: 'electricity',
    baseUnit: 'volt',
    precision: 8,
    units: [
      { name: 'Volt', symbol: 'V', factor: 1 },
      { name: 'Millivolt', symbol: 'mV', factor: 0.001 },
      { name: 'Microvolt', symbol: 'μV', factor: 0.000001 },
      { name: 'Kilovolt', symbol: 'kV', factor: 1000 },
      { name: 'Megavolt', symbol: 'MV', factor: 1000000 },
      { name: 'Abvolt', symbol: 'abV', factor: 0.00000001 },
    ],
  },
  {
    id: 'electric-resistance',
    name: 'Electric Resistance Converter',
    description: 'Convert between different electric resistance units including ohm, kiloohm, and more.',
    category: 'electricity',
    baseUnit: 'ohm',
    precision: 8,
    units: [
      { name: 'Ohm', symbol: 'Ω', factor: 1 },
      { name: 'Milliohm', symbol: 'mΩ', factor: 0.001 },
      { name: 'Microohm', symbol: 'μΩ', factor: 0.000001 },
      { name: 'Kiloohm', symbol: 'kΩ', factor: 1000 },
      { name: 'Megaohm', symbol: 'MΩ', factor: 1000000 },
      { name: 'Abohm', symbol: 'abΩ', factor: 0.000000001 },
    ],
  },
  {
    id: 'electric-resistivity',
    name: 'Electric Resistivity Converter',
    description: 'Convert between different electric resistivity units.',
    category: 'electricity',
    baseUnit: 'ohm meter',
    precision: 8,
    units: [
      { name: 'Ohm Meter', symbol: 'Ω⋅m', factor: 1 },
      { name: 'Ohm Centimeter', symbol: 'Ω⋅cm', factor: 0.01 },
      { name: 'Ohm Inch', symbol: 'Ω⋅in', factor: 0.0254 },
    ],
  },
  {
    id: 'electric-conductance',
    name: 'Electric Conductance Converter',
    description: 'Convert between different electric conductance units including siemens, mho, and more.',
    category: 'electricity',
    baseUnit: 'siemens',
    precision: 8,
    units: [
      { name: 'Siemens', symbol: 'S', factor: 1 },
      { name: 'Millisiemens', symbol: 'mS', factor: 0.001 },
      { name: 'Microsiemens', symbol: 'μS', factor: 0.000001 },
      { name: 'Mho', symbol: 'mho', factor: 1 },
      { name: 'Abmho', symbol: 'abmho', factor: 1000000000 },
    ],
  },
  {
    id: 'electric-conductivity',
    name: 'Electric Conductivity Converter',
    description: 'Convert between different electric conductivity units.',
    category: 'electricity',
    baseUnit: 'siemens per meter',
    precision: 8,
    units: [
      { name: 'Siemens per Meter', symbol: 'S/m', factor: 1 },
      { name: 'Siemens per Centimeter', symbol: 'S/cm', factor: 100 },
      { name: 'Mho per Meter', symbol: 'mho/m', factor: 1 },
      { name: 'Mho per Centimeter', symbol: 'mho/cm', factor: 100 },
    ],
  },
  {
    id: 'electrostatic-capacitance',
    name: 'Electrostatic Capacitance Converter',
    description: 'Convert between different electrostatic capacitance units including farad, microfarad, and more.',
    category: 'electricity',
    baseUnit: 'farad',
    precision: 12,
    units: [
      { name: 'Farad', symbol: 'F', factor: 1 },
      { name: 'Millifarad', symbol: 'mF', factor: 0.001 },
      { name: 'Microfarad', symbol: 'μF', factor: 0.000001 },
      { name: 'Nanofarad', symbol: 'nF', factor: 0.000000001 },
      { name: 'Picofarad', symbol: 'pF', factor: 0.000000000001 },
      { name: 'Abfarad', symbol: 'abF', factor: 1000000000 },
    ],
  },
  {
    id: 'inductance',
    name: 'Inductance Converter',
    description: 'Convert between different inductance units including henry, millihenry, and more.',
    category: 'electricity',
    baseUnit: 'henry',
    precision: 8,
    units: [
      { name: 'Henry', symbol: 'H', factor: 1 },
      { name: 'Millihenry', symbol: 'mH', factor: 0.001 },
      { name: 'Microhenry', symbol: 'μH', factor: 0.000001 },
      { name: 'Nanohenry', symbol: 'nH', factor: 0.000000001 },
      { name: 'Abhenry', symbol: 'abH', factor: 0.000000001 },
    ],
  },

  // Magnetism Converters
  {
    id: 'magnetomotive-force',
    name: 'Magnetomotive Force Converter',
    description: 'Convert between different magnetomotive force units including ampere-turn, gilbert, and more.',
    category: 'magnetism',
    baseUnit: 'ampere turn',
    precision: 8,
    units: [
      { name: 'Ampere-turn', symbol: 'At', factor: 1 },
      { name: 'Gilbert', symbol: 'Gb', factor: 0.795775 },
      { name: 'Milliampere-turn', symbol: 'mAt', factor: 0.001 },
    ],
  },
  {
    id: 'magnetic-field-strength',
    name: 'Magnetic Field Strength Converter',
    description: 'Convert between different magnetic field strength units including A/m, Oe, and more.',
    category: 'magnetism',
    baseUnit: 'ampere per meter',
    precision: 8,
    units: [
      { name: 'Ampere per Meter', symbol: 'A/m', factor: 1 },
      { name: 'Oersted', symbol: 'Oe', factor: 79.5775 },
      { name: 'Ampere per Centimeter', symbol: 'A/cm', factor: 100 },
      { name: 'Ampere per Inch', symbol: 'A/in', factor: 39.3701 },
    ],
  },
  {
    id: 'magnetic-flux',
    name: 'Magnetic Flux Converter',
    description: 'Convert between different magnetic flux units including weber, maxwell, and more.',
    category: 'magnetism',
    baseUnit: 'weber',
    precision: 8,
    units: [
      { name: 'Weber', symbol: 'Wb', factor: 1 },
      { name: 'Maxwell', symbol: 'Mx', factor: 0.00000001 },
      { name: 'Milliweber', symbol: 'mWb', factor: 0.001 },
      { name: 'Microweber', symbol: 'μWb', factor: 0.000001 },
    ],
  },
  {
    id: 'magnetic-flux-density',
    name: 'Magnetic Flux Density Converter',
    description: 'Convert between different magnetic flux density units including tesla, gauss, and more.',
    category: 'magnetism',
    baseUnit: 'tesla',
    precision: 8,
    units: [
      { name: 'Tesla', symbol: 'T', factor: 1 },
      { name: 'Gauss', symbol: 'G', factor: 0.0001 },
      { name: 'Millitesla', symbol: 'mT', factor: 0.001 },
      { name: 'Microtesla', symbol: 'μT', factor: 0.000001 },
      { name: 'Weber per Square Meter', symbol: 'Wb/m²', factor: 1 },
    ],
  },

  // Radiology Converters
  {
    id: 'radiation',
    name: 'Radiation Converter',
    description: 'Convert between different radiation units including becquerel, curie, and more.',
    category: 'radiology',
    baseUnit: 'becquerel',
    precision: 8,
    units: [
      { name: 'Becquerel', symbol: 'Bq', factor: 1 },
      { name: 'Curie', symbol: 'Ci', factor: 37000000000 },
      { name: 'Rutherford', symbol: 'Rd', factor: 1000000 },
      { name: 'Terabecquerel', symbol: 'TBq', factor: 1000000000000 },
    ],
  },
  {
    id: 'radiation-activity',
    name: 'Radiation Activity Converter',
    description: 'Convert between different radiation activity units.',
    category: 'radiology',
    baseUnit: 'becquerel',
    precision: 8,
    units: [
      { name: 'Becquerel', symbol: 'Bq', factor: 1 },
      { name: 'Kilobecquerel', symbol: 'kBq', factor: 1000 },
      { name: 'Megabecquerel', symbol: 'MBq', factor: 1000000 },
      { name: 'Gigabecquerel', symbol: 'GBq', factor: 1000000000 },
      { name: 'Curie', symbol: 'Ci', factor: 37000000000 },
      { name: 'Millicurie', symbol: 'mCi', factor: 37000000 },
    ],
  },
  {
    id: 'radiation-exposure',
    name: 'Radiation Exposure Converter',
    description: 'Convert between different radiation exposure units including roentgen, C/kg, and more.',
    category: 'radiology',
    baseUnit: 'coulomb per kilogram',
    precision: 8,
    units: [
      { name: 'Coulomb per Kilogram', symbol: 'C/kg', factor: 1 },
      { name: 'Roentgen', symbol: 'R', factor: 0.000258 },
      { name: 'Milliroentgen', symbol: 'mR', factor: 0.000000258 },
    ],
  },
  {
    id: 'radiation-absorbed-dose',
    name: 'Radiation Absorbed Dose Converter',
    description: 'Convert between different radiation absorbed dose units including gray, rad, and more.',
    category: 'radiology',
    baseUnit: 'gray',
    precision: 8,
    units: [
      { name: 'Gray', symbol: 'Gy', factor: 1 },
      { name: 'Rad', symbol: 'rad', factor: 0.01 },
      { name: 'Milligray', symbol: 'mGy', factor: 0.001 },
      { name: 'Joule per Kilogram', symbol: 'J/kg', factor: 1 },
    ],
  },

  // Other Converters
  {
    id: 'data-storage',
    name: 'Data Storage Converter',
    description: 'Convert between different data storage units including bytes, kilobytes, megabytes, and more.',
    category: 'other',
    baseUnit: 'byte',
    precision: 6,
    units: [
      { name: 'Bit', symbol: 'bit', factor: 0.125 },
      { name: 'Byte', symbol: 'B', factor: 1 },
      { name: 'Kilobyte', symbol: 'kB', factor: 1000 },
      { name: 'Megabyte', symbol: 'MB', factor: 1000000 },
      { name: 'Gigabyte', symbol: 'GB', factor: 1000000000 },
      { name: 'Terabyte', symbol: 'TB', factor: 1000000000000 },
      { name: 'Kibibyte', symbol: 'KiB', factor: 1024 },
      { name: 'Mebibyte', symbol: 'MiB', factor: 1048576 },
      { name: 'Gibibyte', symbol: 'GiB', factor: 1073741824 },
      { name: 'Tebibyte', symbol: 'TiB', factor: 1099511627776 },
    ],
  },
  {
    id: 'data-transfer',
    name: 'Data Transfer Converter',
    description: 'Convert between different data transfer rate units including bps, kbps, Mbps, and more.',
    category: 'other',
    baseUnit: 'bit per second',
    precision: 6,
    units: [
      { name: 'Bit per Second', symbol: 'bps', factor: 1 },
      { name: 'Kilobit per Second', symbol: 'kbps', factor: 1000 },
      { name: 'Megabit per Second', symbol: 'Mbps', factor: 1000000 },
      { name: 'Gigabit per Second', symbol: 'Gbps', factor: 1000000000 },
      { name: 'Byte per Second', symbol: 'B/s', factor: 8 },
      { name: 'Kilobyte per Second', symbol: 'kB/s', factor: 8000 },
      { name: 'Megabyte per Second', symbol: 'MB/s', factor: 8000000 },
    ],
  },
  {
    id: 'sound',
    name: 'Sound Converter',
    description: 'Convert between different sound units including decibel, bel, and more.',
    category: 'other',
    baseUnit: 'decibel',
    precision: 4,
    units: [
      { name: 'Decibel', symbol: 'dB', factor: 1 },
      { name: 'Bel', symbol: 'B', factor: 10 },
      { name: 'Neper', symbol: 'Np', factor: 8.686 },
    ],
  },
  {
    id: 'typography',
    name: 'Typography Converter',
    description: 'Convert between different typography units including point, pica, pixel, and more.',
    category: 'other',
    baseUnit: 'point',
    precision: 6,
    units: [
      { name: 'Point', symbol: 'pt', factor: 1 },
      { name: 'Pica', symbol: 'pc', factor: 12 },
      { name: 'Pixel', symbol: 'px', factor: 0.75 },
      { name: 'Inch', symbol: 'in', factor: 72 },
      { name: 'Millimeter', symbol: 'mm', factor: 2.834646 },
    ],
  },
  {
    id: 'volume-lumber',
    name: 'Volume Lumber Converter',
    description: 'Convert between different lumber volume units including board feet, cubic meters, and more.',
    category: 'other',
    baseUnit: 'cubic meter',
    precision: 6,
    units: [
      { name: 'Cubic Meter', symbol: 'm³', factor: 1 },
      { name: 'Board Foot', symbol: 'bf', factor: 0.00235974 },
      { name: 'Cubic Foot', symbol: 'ft³', factor: 0.0283168 },
      { name: 'Cubic Inch', symbol: 'in³', factor: 0.0000163871 },
    ],
  },
  {
    id: 'prefixes',
    name: 'Prefixes Converter',
    description: 'Convert between different SI prefixes and their decimal values.',
    category: 'other',
    baseUnit: 'unit',
    precision: 20,
    units: [
      { name: 'Yotta', symbol: 'Y', factor: 1e24 },
      { name: 'Zetta', symbol: 'Z', factor: 1e21 },
      { name: 'Exa', symbol: 'E', factor: 1e18 },
      { name: 'Peta', symbol: 'P', factor: 1e15 },
      { name: 'Tera', symbol: 'T', factor: 1e12 },
      { name: 'Giga', symbol: 'G', factor: 1e9 },
      { name: 'Mega', symbol: 'M', factor: 1e6 },
      { name: 'Kilo', symbol: 'k', factor: 1e3 },
      { name: 'Unit', symbol: '', factor: 1 },
      { name: 'Milli', symbol: 'm', factor: 1e-3 },
      { name: 'Micro', symbol: 'μ', factor: 1e-6 },
      { name: 'Nano', symbol: 'n', factor: 1e-9 },
      { name: 'Pico', symbol: 'p', factor: 1e-12 },
      { name: 'Femto', symbol: 'f', factor: 1e-15 },
      { name: 'Atto', symbol: 'a', factor: 1e-18 },
      { name: 'Zepto', symbol: 'z', factor: 1e-21 },
      { name: 'Yocto', symbol: 'y', factor: 1e-24 },
    ],
  },
  {
    id: 'numbers',
    name: 'Numbers Converter',
    description: 'Convert between different number systems including decimal, binary, hexadecimal, and more.',
    category: 'other',
    baseUnit: 'decimal',
    precision: 0,
    units: [
      { name: 'Decimal', symbol: 'dec', factor: 1 },
      { name: 'Binary', symbol: 'bin', factor: 1 },
      { name: 'Octal', symbol: 'oct', factor: 1 },
      { name: 'Hexadecimal', symbol: 'hex', factor: 1 },
    ],
  },
  {
    id: 'case',
    name: 'Case Converter',
    description: 'Convert text between different case formats including uppercase, lowercase, title case, and more.',
    category: 'other',
    baseUnit: 'original',
    precision: 0,
    units: [
      { name: 'Original', symbol: 'orig', factor: 1 },
      { name: 'Uppercase', symbol: 'UPPER', factor: 1 },
      { name: 'Lowercase', symbol: 'lower', factor: 1 },
      { name: 'Title Case', symbol: 'Title', factor: 1 },
      { name: 'Sentence case', symbol: 'Sentence', factor: 1 },
      { name: 'camelCase', symbol: 'camel', factor: 1 },
      { name: 'PascalCase', symbol: 'Pascal', factor: 1 },
      { name: 'snake_case', symbol: 'snake', factor: 1 },
      { name: 'kebab-case', symbol: 'kebab', factor: 1 },
    ],
  },
  {
    id: 'volume-dry',
    name: 'Volume Dry Converter',
    description: 'Convert between different dry volume units including bushel, peck, quart dry, and more.',
    category: 'common',
    baseUnit: 'liter',
    precision: 8,
    units: [
      { name: 'Liter', symbol: 'L', factor: 1 },
      { name: 'Bushel (US)', symbol: 'bu', factor: 35.2391 },
      { name: 'Peck (US)', symbol: 'pk', factor: 8.80977 },
      { name: 'Quart Dry (US)', symbol: 'qt dry', factor: 1.10122 },
      { name: 'Pint Dry (US)', symbol: 'pt dry', factor: 0.550610 },
    ],
  },
];